apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  namespace: steam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - name: producer
        image: manoelpg/producer:v1.0
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 250m  # Limite de CPU adicionado
            memory: 100Mi  # Limite de memória adicionado
