version: "3.8"

services:
  app:
    build:
      context: ../../
      ssh:
        - default
      target: app_dev
      dockerfile: docker/Dockerfile
      args:
        - HOST_UID=${HOST_UID:-0}
        - HOST_USER=${HOST_USER:-root}
        - HOST_GID=${HOST_GID:-0}
        - HOST_GROUP=${HOST_GROUP:-root}
    user: ${HOST_UID:-0}
    image: steam_app:dev
    networks:
      - steamcomm
    environment:
      SSH_AUTH_SOCK: "/ssh-auth.sock"
    volumes:
      # SSH
      -  $SSH_AUTH_SOCK:/ssh-auth.sock
      - ~/.ssh/known_hosts:/home/${HOST_USER}/.ssh/known_hosts:ro
      # APP
      - ../../:/var/www/steam


networks:
  steamcomm:

