apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit
  namespace: steam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
      - name: streamlit
        image: manoelpg/streamlit:v1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8501
        volumeMounts:
        - name: host-volume
          mountPath: /app/data
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
      volumes:
      - name: host-volume
        hostPath:
          path: /root/steam/data
          type: Directory
